{{ if .Values.fdb.deploy -}}
apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    app: fdb
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "chart.fullname" . }}-fdb
spec:
  version: 6.2.20
  faultDomain:
    key: foundationdb.org/none
  processCounts:
    storage: 5
    log: 4
  #  stateless: -1
  #customParameters:
  #  - "knob_disable_posix_kernel_aio=1"
  processes:
    general:
      volumeClaim:
        spec:
          storageClassName: {{ .Values.fdb.storageClass }}
      podTemplate:
        spec:
          securityContext:
            fsGroup: 0
          containers:
            - name: foundationdb
              securityContext:
                runAsUser: 0
              resources:
                requests:
                  cpu: 100m
                  memory: 1Gi
                limits:
                  cpu: 1000m
                  memory: 4Gi
            - name: foundationdb-kubernetes-sidecar
              securityContext:
                runAsUser: 0
          initContainers:
            - name: foundationdb-kubernetes-init
              securityContext:
                runAsUser: 0
    storage:
      volumeClaim:
        spec:
          storageClassName: {{ .Values.fdb.storageClass }}
      podTemplate:
        spec:
          securityContext:
            fsGroup: 0
          containers:
            - name: foundationdb
              securityContext:
                runAsUser: 0
              resources:
                requests:
                  cpu: 1000m
                  memory: 4Gi
                limits:
                  cpu: 3000m
                  memory: 8Gi
            - name: foundationdb-kubernetes-sidecar
              securityContext:
                runAsUser: 0
          initContainers:
            - name: foundationdb-kubernetes-init
              securityContext:
                runAsUser: 0
          tolerations:
            - key: dedicated
              operator: Equal
              value: fdb
              effect: NoSchedule
    log:
      volumeClaim:
        spec:
          storageClassName: {{ .Values.fdb.storageClass }}
      podTemplate:
        spec:
          securityContext:
            fsGroup: 0
          containers:
            - name: foundationdb
              securityContext:
                runAsUser: 0
              resources:
                requests:
                  cpu: 500m
                  memory: 4Gi
                limits:
                  cpu: 2000m
                  memory: 8Gi
            - name: foundationdb-kubernetes-sidecar
              securityContext:
                runAsUser: 0
          initContainers:
            - name: foundationdb-kubernetes-init
              securityContext:
                runAsUser: 0
          tolerations:
          - key: dedicated
            operator: Equal
            value: fdb
            effect: NoSchedule
{{- end }}
